// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7V3PDFET_hwgUnhlGJ9Z25zBE3bfe7w',
    appId: '1:915556525451:android:9df53f7be9bcfa00b63b8e',
    messagingSenderId: '915556525451',
    projectId: 'medicall-f8000',
    storageBucket: 'medicall-f8000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYuJYk2bIGmiLJrOZPGrysN5ZX-072lZY',
    appId: '1:915556525451:ios:6824ccb00821ced5b63b8e',
    messagingSenderId: '915556525451',
    projectId: 'medicall-f8000',
    storageBucket: 'medicall-f8000.firebasestorage.app',
    androidClientId: '915556525451-8o529t9tt97qmvlihf5ls0gp8io396hn.apps.googleusercontent.com',
    iosClientId: '915556525451-b2a1u3ql6a7r07emm1ut75trh18of22a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstWtfApp',
  );

}